version: '3.8'

services:

  mysql:
    image: mysql:8.0.31
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - '3306:3306'

  postgresdb:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'

  node-app:
    build: ./gate-simulator
    ports:
      - '9999:9999'